name: Build

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:

      # if this action fails with "Specified target combination is not valid" error, try running aqt locally,
      # using `aqt list-tool windows desktop tools_ifw` and checking the version number.
      # For more info see https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-tools
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          tools: 'tools_ifw,qt.tools.ifw.45'
          tools-only: 'true'

      - name: Add Qt tools to PATH
        run: Add-Content $env:GITHUB_PATH $env:IQTA_TOOLS\QtInstallerFramework\4.5\bin

      - name: Create distributable
        shell: cmd
        run: binarycreator.exe --help
